### ISSUE TITLE
Unknown command: rootpw

### ISSUE THREAD

**Issue by noctrnal** [sscheib/ansible_satellite#1]
Getting a failure on validating the kickstart:

TASK [rhel_iso_kickstart : Ensure ksvalidator is installed] ********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [rhel_iso_kickstart : Validate kickstart] *********************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["ksvalidator", "/root/workdir/src/ks.cfg"], "delta": "0:00:00.202545", "end": "2024-05-10 22:02:03.390479", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2024-05-10 22:02:03.187934", "stderr": "The following problem occurred on line 67 of the kickstart file:\n\nUnknown command: rootpw --iscrypted $6$K4NsjXpdTsi9PS1Q$foxIkuXuAgX0h7vfMjAKvD7i0QCYb4n.c7pJk2uasvPnFA32M95hwke9mcucjejqHBmUlk478P.wFjxx.r9J./", "stderr_lines": ["The following problem occurred on line 67 of the kickstart file:", "", "Unknown command: rootpw --iscrypted $6$K4NsjXpdTsi9PS1Q$foxIkuXuAgX0h7vfMjAKvD7i0QCYb4n.c7pJk2uasvPnFA32M95hwke9mcucjejqHBmUlk478P.wFjxx.r9J./"], "stdout": "", "stdout_lines": []}

TASK [rhel_iso_kickstart : Show command output when the kickstart validation failed] *******************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "The following problem occurred on line 67 of the kickstart file:\n\nUnknown command: rootpw --iscrypted $6$K4NsjXpdTsi9PS1Q$foxIkuXuAgX0h7vfMjAKvD7i0QCYb4n.c7pJk2uasvPnFA32M95hwke9mcucjejqHBmUlk478P.wFjxx.r9J./"
}

TASK [rhel_iso_kickstart : Kickstart validation failed] ************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Kickstart validation failed"}

**Comment by sscheib** [comment]
I think I've [fixed](https://github.com/sscheib/ansible-role-rhel_iso_kickstart/commit/4019c86e7a7b145d09ee8b57844a3ae0b2484631) this on the role back then, but totally forgot to add the later role releases into the `collections/requirements.yml`.

I just updated `collections/requirements.yml` to use the latest version of my role.

Can you go ahead and give it a try?

**Comment by noctrnal** [comment]
Thank you for the quick update. Worked like a charm without error on build!
